name: Publish Python 🐍 distributions 📦 to PyPI
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  publish-and-create-releases:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.2.0b3"]
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Install poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      -
        name: Add poetry plugin
        run: |
          pip install poetry-version-plugin
      -
        name: PyPI setting
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      -
        name: build pandoc_pdf
        run: |
          poetry build
      -
        name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        run: |
          poetry publish
      -
        name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/pandoc_pdf*.tar.gz
            dist/pandoc_pdf*.whl
